**Python Descriptive Statistics** process describes the basic features of data in a study. It delivers summaries on the sample and the measures and does not use the data to learn about the population it represents.

Under descriptive statistics, fall two sets of properties- central tendency and dispersion. <br>
**Python Central tendency** characterizes one central value for the entire distribution. Measures under this include mean, median, and mode. 
**Python Dispersion** is the term for a practice that characterizes how apart the members of the distribution are from the center and from each other. Variance/Standard Deviation is one such measure of variability.

In [4]:
import numpy as np
import pandas as pd
data=pd.read_csv("scooter_may2019.csv")
print(data)

       TripID  TripDuration  TripDistance                 StartTime  \
0        1047          2866          9521  2019-05-13T20:30:00.000Z   
1        1053          1387          5753  2019-05-13T20:30:00.000Z   
2        1060           962          1630  2019-05-13T20:30:00.000Z   
3        1048           423          2149  2019-05-13T20:30:00.000Z   
4        1042          3813          6943  2019-05-13T20:30:00.000Z   
...       ...           ...           ...                       ...   
39752   38617           219           656  2019-05-31T12:00:00.000Z   
39753   38464           698          2873  2019-05-31T05:30:00.000Z   
39754   38252          5966          4313  2019-05-31T03:30:00.000Z   
39755   38256           557          1363  2019-05-31T03:30:00.000Z   
39756   38258          1362           947  2019-05-31T03:30:00.000Z   

                        EndTime  StartCenterlineID StartCenterlineType  \
0      2019-05-13T21:00:00.000Z                NaN               trail   

In [69]:
df = pd.DataFrame(data)
df

TripID  TripDuration  TripDistance                 StartTime  \
0        1047          2866          9521  2019-05-13T20:30:00.000Z   
1        1053          1387          5753  2019-05-13T20:30:00.000Z   
2        1060           962          1630  2019-05-13T20:30:00.000Z   
3        1048           423          2149  2019-05-13T20:30:00.000Z   
4        1042          3813          6943  2019-05-13T20:30:00.000Z   
...       ...           ...           ...                       ...   
39752   38617           219           656  2019-05-31T12:00:00.000Z   
39753   38464           698          2873  2019-05-31T05:30:00.000Z   
39754   38252          5966          4313  2019-05-31T03:30:00.000Z   
39755   38256           557          1363  2019-05-31T03:30:00.000Z   
39756   38258          1362           947  2019-05-31T03:30:00.000Z   

                        EndTime  StartCenterlineID StartCenterlineType  \
0      2019-05-13T21:00:00.000Z                NaN               trail   
1      2019-05-13T21:00:00.000Z            17242.0              street   
2      2019-05-13T21:00:00.000Z            19502.0              street   
3      2019-05-13T20:30:00.000Z            18092.0              street   
4      2019-05-13T21:30:00.000Z            18617.0              street   
...                         ...                ...                 ...   
39752  2019-05-31T12:00:00.000Z            16717.0              street   
39753  2019-05-31T06:00:00.000Z            18343.0              street   
39754  2019-05-31T05:00:00.000Z            20799.0              street   
39755  2019-05-31T03:30:00.000Z            16942.0              street   
39756  2019-05-31T04:00:00.000Z            16901.0              street   

       EndCenterlineID EndCenterlineType  ObjectId  
0                  NaN             trail         1  
1              11720.0            street         2  
2              17104.0            street         3  
3              15446.0            street         4  
4                  NaN             trail         5  
...                ...               ...       ...  
39752          19544.0            street     36996  
39753          16803.0            street     36997  
39754          17086.0            street     36998  
39755          19782.0            street     36999  
39756          17606.0            street     37000  

[39757 rows x 10 columns]

In [70]:
distance = df[df.columns[2]]
distance

0        9521
1        5753
2        1630
3        2149
4        6943
         ... 
39752     656
39753    2873
39754    4313
39755    1363
39756     947
Name: TripDistance, Length: 39757, dtype: int64

In [71]:
#Total distance
print("Total Distance covered in May2019: ",distance.sum())

Total Distance covered in May2019:  91165407


In [72]:
#mean
print("Mean Distance: ",distance.mean())

Mean Distance:  2293.0655482053476


In [73]:
#standard deviation
print("Standard deviation of distances: ",distance.std())

Standard deviation of distances:  2293.3688083856714


In [74]:
#max
print("Maximum Distance covered in May2019: ",distance.max())

Maximum Distance covered in May2019:  32732


In [75]:
#min
print("Minimum Distance covered in May2019: ",distance.min())

Minimum Distance covered in May2019:  1


In [89]:
#Mode
print("Mode of distance: ",distance.mode())

Mode of distance:  0    4
dtype: int64


In [90]:
#count - Number of non-null observations
print("Count: ",distance.count())

Count:  39757


In [86]:
print("Product : ",distance.prod())

Product :  0


In [87]:
print("Cummuative Sum : ",distance.cumsum())

Cummuative Sum :  0            9521
1           15274
2           16904
3           19053
4           25996
           ...   
39752    91155911
39753    91158784
39754    91163097
39755    91164460
39756    91165407
Name: TripDistance, Length: 39757, dtype: int64


In [88]:
print("Cummuative Product : ",distance.cumprod())

Cummuative Product :  0                       9521
1                   54774313
2                89282130190
3            191867297778310
4        1332134648474806330
                ...         
39752                      0
39753                      0
39754                      0
39755                      0
39756                      0
Name: TripDistance, Length: 39757, dtype: int64


**Summarising data**

In [91]:
print(df.describe())


             TripID  TripDuration  TripDistance  StartCenterlineID  \
count  39757.000000  39757.000000  39757.000000       35217.000000   
mean   21623.625726   1072.624745   2293.065548       17648.990516   
std    11969.840416   1184.074724   2293.368808        3152.013501   
min     1000.000000      3.000000      1.000000       10009.000000   
25%    11215.000000    342.000000    741.000000       16201.000000   
50%    21612.000000    653.000000   1549.000000       17242.000000   
75%    31940.000000   1328.000000   3106.000000       18950.000000   
max    42502.000000  12371.000000  32732.000000       26146.000000   

       EndCenterlineID      ObjectId  
count     34031.000000  39757.000000  
mean      17679.711116  19879.000000  
std        3228.660070  11477.001663  
min       10006.000000      1.000000  
25%       16086.000000   9940.000000  
50%       17240.000000  19879.000000  
75%       19245.000000  29818.000000  
max       26147.000000  39757.000000  


**object − Summarizes String columns<br>
number − Summarizes Numeric columns<br>
all − Summarizes all columns together (Should not pass it as a list value)**

In [92]:
print(df.describe(include=['object']))


                       StartTime                   EndTime  \
count                      39757                     39757   
unique                       861                       866   
top     2019-05-25T20:30:00.000Z  2019-05-25T21:30:00.000Z   
freq                         221                       209   

       StartCenterlineType EndCenterlineType  
count                39757             39757  
unique                   2                 2  
top                 street            street  
freq                 35217             34031  


In [93]:
print(df.describe(include=['number']))


             TripID  TripDuration  TripDistance  StartCenterlineID  \
count  39757.000000  39757.000000  39757.000000       35217.000000   
mean   21623.625726   1072.624745   2293.065548       17648.990516   
std    11969.840416   1184.074724   2293.368808        3152.013501   
min     1000.000000      3.000000      1.000000       10009.000000   
25%    11215.000000    342.000000    741.000000       16201.000000   
50%    21612.000000    653.000000   1549.000000       17242.000000   
75%    31940.000000   1328.000000   3106.000000       18950.000000   
max    42502.000000  12371.000000  32732.000000       26146.000000   

       EndCenterlineID      ObjectId  
count     34031.000000  39757.000000  
mean      17679.711116  19879.000000  
std        3228.660070  11477.001663  
min       10006.000000      1.000000  
25%       16086.000000   9940.000000  
50%       17240.000000  19879.000000  
75%       19245.000000  29818.000000  
max       26147.000000  39757.000000  


### NumPy Random

**Generating random numbers**

In [98]:
from numpy import random
x = random.randint(50)
print(x)

44


In [100]:
#The random module's rand() method returns a random float between 0 and 1.
x = random.rand(50)
print(x)

[0.68161882 0.65004326 0.42751654 0.36048943 0.2325223  0.30703076
 0.84318482 0.95703804 0.21780229 0.26817462 0.74684197 0.91070647
 0.87068872 0.98559957 0.65588976 0.78572599 0.43357807 0.48963087
 0.85369636 0.8525568  0.48553808 0.97677142 0.52430453 0.99084509
 0.67077334 0.03123531 0.59765745 0.59454068 0.41152308 0.84868812
 0.44339514 0.26354359 0.83554831 0.94912332 0.05400489 0.11001282
 0.80147946 0.84733877 0.94641405 0.24487419 0.17914561 0.37244969
 0.41914489 0.10309044 0.28934049 0.76956771 0.44609064 0.10752676
 0.18166133 0.52645388]


numpy.random.random() returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

numpy.random.randint() returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), i.e. in the interval [low, high).


In [94]:
np.random.random((3,2))

array([[0.46928691, 0.31263232],
       [0.79274171, 0.55454541],
       [0.67030655, 0.87703274]])

In [95]:
np.random.randint(low = 1, high = 10, size = (3,2))

array([[1, 1],
       [4, 4],
       [6, 4]])

**Choice method**
The choice() method allows you to generate a random value based on an array of values.

In [103]:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

7


In [104]:
x = random.choice([3, 5, 7, 9],size=(2,2))
print(x)

[[9 3]
 [9 5]]


**Random Distribution**

A random distribution is a set of random numbers that follow a certain probability density function.

Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

In [107]:
# Generate an array of size= 2X3, where each value has to be 1,2,3 or 4
# The probability for the value to be 1 is set to be 0.1
# The probability for the value to be 2 is set to be 0.3
# The probability for the value to be 3 is set to be 0.6
# The probability for the value to be 4 is set to be 0

x = random.choice([1,2,3,4], p=[0.1, 0.3, 0.6, 0.0], size=(2,3))

print(x)

[[1 3 2]
 [3 3 3]]


### SciPy
The SciPy is an open-source scientific library of Python that is distributed under a BSD license. It is used to solve the complex scientific and mathematical problems. It is built on top of the Numpy extension, which means if we import the SciPy, there is no need to import Numpy.

**SciPy Stats**
The scipy.stats contains a large number of statistics, probability distributions functions.

rv_continuos	It is a base class to construct specific distribution classes and instances for continuous random variable.<br>
rv_discrete	It is a base class to construct specific distribution classes and instances for discrete random variables.<br>
rv_histogram	It can be inherited from rv_continuous class. It generates a distribution given by a histogram.

In [2]:
from scipy.stats import norm

**Normal Continuous Random Variable**
A probability distribution in which the random variable X can take any value is continuous random variable. The location (loc) keyword specifies the mean. The scale (scale) keyword specifies the standard deviation.

The cumulative distribution function (CDF) of a real-valued random variable X, or just distribution function of X, evaluated at x, is the probability that X will take a value less than or equal to x

In [5]:
print(norm.cdf(np.array([3,-1., 0, 1, 2, 4, -2, 5])))  

[0.9986501  0.15865525 0.5        0.84134475 0.97724987 0.99996833
 0.02275013 0.99999971]


In [6]:
print(norm.rvs(loc = 0, scale = 1,size=(2,2)))

[[-0.33541738 -0.02932694]
 [ 0.00864725 -0.94280673]]


The uniform function generates a uniform continuous variable between the specified interval via its loc and scale arguments. This distribution is constant between loc and loc + scale. The size arguments describe the number of random variates